from tkinter import *


def pressed(event):
    global scvalue
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(scvalue.get())
            scvalue.set(value)

    elif text == "C":
        scvalue.set("")
    else:
        scvalue.set(scvalue.get() + text)


w = Tk()
w.title('Calculator')
# frameset=Frame(w)
# frameset.pack()
scvalue = StringVar()
scvalue.set("")
t = Entry(w, width=53, font=('lucida', 35), bd=1, textvar=scvalue)
t.pack(fill=X, padx=10, pady=10)
f = Frame(w, bg='#D3D3D3')
l1 = Button(f, text='7', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='8', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='9', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
f.pack()

f = Frame(w, bg='#D3D3D3')
l1 = Button(f, text='4', width=13, height=2, bg='black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='5', width=13, height=2, bg='black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='6', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
f.pack()

f = Frame(w, bg='#D3D3D3')
l1 = Button(f, text='1', width=13, height=2, bg='black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='2', width=13, height=2, bg='black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='3', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
f.pack()

f = Frame(w, bg='#D3D3D3')
l1 = Button(f, text='0', width=13, height=2, bg='black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='00', width=13, height=2, bg='black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='.', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
f.pack()

f = Frame(w, bg='#D3D3D3')
l1 = Button(f, text='+', width=13, height=2, bg='Black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='-', width=13, height=2, bg='Black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='%', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
f.pack()

f = Frame(w, bg='#D3D3D3')
l1 = Button(f, text='C', width=13, height=2, bg='Black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='/', width=13, height=2, bg='Black', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
l1 = Button(f, text='=', width=13, height=2, bg='Red', fg='White')
l1.pack(side=LEFT, padx=10, pady=15)
l1.bind('<Button-1>', pressed)
f.pack()
w.maxsize(400, 550)
w.minsize(400, 550)
w.mainloop()